[package]
name = "barbershop"
version = "0.1.0"
publish = false
edition = "2018"

[dependencies]
envy = "0.4"
hex = "0.3"
lambda_http = "0.1"
lambda_runtime = "0.2"
reqwest = "0.9"
rust-crypto = "0.2"
serde = "1.0"
serde_derive = "1.0"